name: Build Package

on:
  release:
    types: [published]
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Zip code to distribute
      run: |
        zip -r pgmatlab.zip pgmatlab/*

    - name: Upload code to distribute
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: pgmatlab.zip

    - name: Append distribution code to release
      uses: softprops/action-gh-release@v2
      with:
        files: pgmatlab.zip